import { MASTER_REPLACES, masterRoot } from './skillAliases';
/**
 * Skill definitions as configured by the OpenMU server we play against
 * (src/Persistence/Initialization/VersionSeasonSix/SkillsInitializer.cs).
 * Generated - do not edit by hand. Numbers are the wire SkillNumber.
 */

export type SkillType =
  | "DirectHit"
  | "AreaSkillAutomaticHits"
  | "Other"
  | "Buff"
  | "Regeneration"
  | "SummonMonster"
  | "AreaSkillExplicitTarget"
  | "PassiveBoost";

export type SkillTargetKind =
  | "Explicit"
  | "ExplicitWithImplicitInRange"
  | "ImplicitParty"
  | "ImplicitPlayer";

export type SkillDamageType = "Wizardry" | "None" | "Physical" | "Fenrir" | "Curse";

export interface SkillDefinition {
  num: number;
  name: string;
  /** OpenMU CharacterClasses flag expression (informational). */
  classes: string;
  damageType: SkillDamageType;
  damage: number;
  /** Max cast distance in tiles (0 = self/any). */
  distance: number;
  ag: number;
  mana: number;
  level: number;
  energy: number;
  type: SkillType;
  target: SkillTargetKind;
  range: number;
}

export const SKILL_DEFINITIONS: readonly SkillDefinition[] = [
  {"num":1,"name":"Poison","classes":"AllMagicians","damageType":"Wizardry","damage":12,"distance":6,"ag":0,"mana":42,"level":0,"energy":140,"type":"DirectHit","target":"Explicit","range":0},
  {"num":2,"name":"Meteorite","classes":"AllMagicians | AllSummoners","damageType":"Wizardry","damage":21,"distance":6,"ag":0,"mana":12,"level":0,"energy":104,"type":"DirectHit","target":"Explicit","range":0},
  {"num":3,"name":"Lightning","classes":"AllMagicians","damageType":"Wizardry","damage":17,"distance":6,"ag":0,"mana":15,"level":0,"energy":72,"type":"DirectHit","target":"Explicit","range":0},
  {"num":4,"name":"Fire Ball","classes":"AllMagicians | AllSummoners","damageType":"Wizardry","damage":8,"distance":6,"ag":0,"mana":3,"level":0,"energy":40,"type":"DirectHit","target":"Explicit","range":0},
  {"num":5,"name":"Flame","classes":"AllMagicians","damageType":"Wizardry","damage":25,"distance":6,"ag":0,"mana":50,"level":0,"energy":160,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":6,"name":"Teleport","classes":"SoulMasterAndGrandMaster","damageType":"Wizardry","damage":0,"distance":6,"ag":0,"mana":30,"level":0,"energy":88,"type":"Other","target":"Explicit","range":0},
  {"num":7,"name":"Ice","classes":"AllMagicians | AllSummoners","damageType":"Wizardry","damage":10,"distance":6,"ag":0,"mana":38,"level":0,"energy":120,"type":"DirectHit","target":"Explicit","range":0},
  {"num":8,"name":"Twister","classes":"AllMagicians","damageType":"Wizardry","damage":35,"distance":6,"ag":0,"mana":60,"level":0,"energy":180,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":9,"name":"Evil Spirit","classes":"AllMagicians","damageType":"Wizardry","damage":45,"distance":7,"ag":0,"mana":90,"level":0,"energy":220,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":10,"name":"Hellfire","classes":"AllMagicians","damageType":"Wizardry","damage":120,"distance":4,"ag":0,"mana":160,"level":0,"energy":260,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":11,"name":"Power Wave","classes":"AllMagicians | AllSummoners","damageType":"Wizardry","damage":14,"distance":6,"ag":0,"mana":5,"level":0,"energy":56,"type":"DirectHit","target":"Explicit","range":0},
  {"num":12,"name":"Aqua Beam","classes":"AllMagicians","damageType":"Wizardry","damage":80,"distance":6,"ag":0,"mana":140,"level":0,"energy":345,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":13,"name":"Cometfall","classes":"AllMagicians","damageType":"Wizardry","damage":70,"distance":3,"ag":0,"mana":150,"level":0,"energy":436,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":14,"name":"Inferno","classes":"AllMagicians","damageType":"Wizardry","damage":100,"distance":4,"ag":0,"mana":200,"level":0,"energy":578,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":15,"name":"Teleport Ally","classes":"SoulMasterAndGrandMaster","damageType":"None","damage":0,"distance":6,"ag":25,"mana":90,"level":0,"energy":644,"type":"Other","target":"Explicit","range":0},
  {"num":16,"name":"Soul Barrier","classes":"SoulMasterAndGrandMaster","damageType":"None","damage":0,"distance":6,"ag":22,"mana":70,"level":0,"energy":408,"type":"Buff","target":"Explicit","range":0},
  {"num":17,"name":"Energy Ball","classes":"AllMagicians","damageType":"Wizardry","damage":3,"distance":6,"ag":0,"mana":1,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":18,"name":"Defense","classes":"AllKnightsLordsAndMGs","damageType":"None","damage":0,"distance":0,"ag":0,"mana":30,"level":0,"energy":0,"type":"Buff","target":"Explicit","range":0},
  {"num":19,"name":"Falling Slash","classes":"AllKnightsLordsAndMGs | AllFighters","damageType":"Physical","damage":0,"distance":3,"ag":0,"mana":9,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":20,"name":"Lunge","classes":"AllKnightsLordsAndMGs","damageType":"Physical","damage":0,"distance":2,"ag":0,"mana":9,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":21,"name":"Uppercut","classes":"AllKnightsLordsAndMGs","damageType":"Physical","damage":0,"distance":2,"ag":0,"mana":8,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":22,"name":"Cyclone","classes":"AllKnightsLordsAndMGs","damageType":"Physical","damage":0,"distance":2,"ag":0,"mana":9,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":23,"name":"Slash","classes":"AllKnightsLordsAndMGs","damageType":"Physical","damage":0,"distance":2,"ag":0,"mana":10,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":24,"name":"Triple Shot","classes":"AllElfs","damageType":"Physical","damage":0,"distance":6,"ag":0,"mana":5,"level":0,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":26,"name":"Heal","classes":"AllElfs","damageType":"None","damage":0,"distance":6,"ag":0,"mana":20,"level":0,"energy":52,"type":"Regeneration","target":"Explicit","range":0},
  {"num":27,"name":"Greater Defense","classes":"AllElfs","damageType":"None","damage":0,"distance":6,"ag":0,"mana":30,"level":0,"energy":72,"type":"Buff","target":"Explicit","range":0},
  {"num":28,"name":"Greater Damage","classes":"AllElfs","damageType":"None","damage":0,"distance":6,"ag":0,"mana":40,"level":0,"energy":92,"type":"Buff","target":"Explicit","range":0},
  {"num":30,"name":"Summon Goblin","classes":"AllElfs","damageType":"None","damage":0,"distance":0,"ag":0,"mana":40,"level":0,"energy":90,"type":"SummonMonster","target":"Explicit","range":0},
  {"num":31,"name":"Summon Stone Golem","classes":"AllElfs","damageType":"None","damage":0,"distance":0,"ag":0,"mana":70,"level":0,"energy":170,"type":"SummonMonster","target":"Explicit","range":0},
  {"num":32,"name":"Summon Assassin","classes":"AllElfs","damageType":"None","damage":0,"distance":0,"ag":0,"mana":110,"level":0,"energy":190,"type":"SummonMonster","target":"Explicit","range":0},
  {"num":33,"name":"Summon Elite Yeti","classes":"AllElfs","damageType":"None","damage":0,"distance":0,"ag":0,"mana":160,"level":0,"energy":230,"type":"SummonMonster","target":"Explicit","range":0},
  {"num":34,"name":"Summon Dark Knight","classes":"AllElfs","damageType":"None","damage":0,"distance":0,"ag":0,"mana":200,"level":0,"energy":250,"type":"SummonMonster","target":"Explicit","range":0},
  {"num":35,"name":"Summon Bali","classes":"AllElfs","damageType":"None","damage":0,"distance":0,"ag":0,"mana":250,"level":0,"energy":260,"type":"SummonMonster","target":"Explicit","range":0},
  {"num":36,"name":"Summon Soldier","classes":"AllElfs","damageType":"None","damage":0,"distance":0,"ag":0,"mana":350,"level":0,"energy":280,"type":"SummonMonster","target":"Explicit","range":0},
  {"num":38,"name":"Decay","classes":"SoulMasterAndGrandMaster","damageType":"Wizardry","damage":95,"distance":6,"ag":7,"mana":110,"level":0,"energy":953,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":39,"name":"Ice Storm","classes":"SoulMasterAndGrandMaster","damageType":"Wizardry","damage":80,"distance":6,"ag":5,"mana":100,"level":0,"energy":849,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":40,"name":"Nova","classes":"SoulMasterAndGrandMaster","damageType":"Wizardry","damage":0,"distance":6,"ag":0,"mana":0,"level":100,"energy":1052,"type":"DirectHit","target":"Explicit","range":0},
  {"num":41,"name":"Twisting Slash","classes":"AllKnights | AllMGs","damageType":"Physical","damage":0,"distance":2,"ag":10,"mana":10,"level":0,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":42,"name":"Rageful Blow","classes":"BladeKnightAndBladeMaster","damageType":"Physical","damage":60,"distance":3,"ag":20,"mana":25,"level":170,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":43,"name":"Death Stab","classes":"BladeKnightAndBladeMaster","damageType":"Physical","damage":70,"distance":2,"ag":12,"mana":15,"level":160,"energy":0,"type":"DirectHit","target":"ExplicitWithImplicitInRange","range":1},
  {"num":44,"name":"Crescent Moon Slash","classes":"AllKnights","damageType":"Physical","damage":90,"distance":4,"ag":15,"mana":22,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":45,"name":"Lance","classes":"SoulMasterAndGrandMaster | AllSummoners","damageType":"Wizardry","damage":90,"distance":6,"ag":10,"mana":150,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":46,"name":"Starfall","classes":"AllElfs","damageType":"Physical","damage":120,"distance":8,"ag":15,"mana":20,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":47,"name":"Impale","classes":"AllKnights | AllMGs","damageType":"Physical","damage":15,"distance":3,"ag":0,"mana":8,"level":28,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":48,"name":"Swell Life","classes":"AllKnights","damageType":"None","damage":0,"distance":0,"ag":24,"mana":22,"level":120,"energy":0,"type":"Buff","target":"ImplicitParty","range":0},
  {"num":49,"name":"Fire Breath","classes":"AllKnights","damageType":"Physical","damage":30,"distance":3,"ag":0,"mana":9,"level":110,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":50,"name":"Flame of Evil (Monster)","classes":"None","damageType":"None","damage":120,"distance":0,"ag":0,"mana":160,"level":60,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":51,"name":"Ice Arrow","classes":"MuseElfAndHighElf","damageType":"Physical","damage":105,"distance":8,"ag":12,"mana":10,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":52,"name":"Penetration","classes":"AllElfs","damageType":"Physical","damage":70,"distance":6,"ag":9,"mana":7,"level":130,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":55,"name":"Fire Slash","classes":"AllMGs","damageType":"Physical","damage":80,"distance":2,"ag":20,"mana":15,"level":0,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":56,"name":"Power Slash","classes":"AllMGs","damageType":"Physical","damage":0,"distance":5,"ag":0,"mana":15,"level":0,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":57,"name":"Spiral Slash","classes":"AllMGs","damageType":"Physical","damage":75,"distance":5,"ag":15,"mana":20,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":58,"name":"Nova (Start)","classes":"SoulMasterAndGrandMaster","damageType":"None","damage":0,"distance":0,"ag":45,"mana":0,"level":100,"energy":1052,"type":"Other","target":"Explicit","range":0},
  {"num":60,"name":"Force","classes":"AllLords","damageType":"Physical","damage":10,"distance":4,"ag":0,"mana":10,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":61,"name":"Fire Burst","classes":"AllLords","damageType":"Physical","damage":100,"distance":6,"ag":0,"mana":25,"level":0,"energy":79,"type":"DirectHit","target":"ExplicitWithImplicitInRange","range":1},
  {"num":62,"name":"Earthshake","classes":"AllLords","damageType":"Physical","damage":150,"distance":10,"ag":50,"mana":0,"level":0,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":63,"name":"Summon","classes":"AllLords","damageType":"None","damage":0,"distance":0,"ag":30,"mana":70,"level":0,"energy":153,"type":"Other","target":"Explicit","range":0},
  {"num":64,"name":"Increase Critical Damage","classes":"AllLords","damageType":"None","damage":0,"distance":0,"ag":50,"mana":50,"level":0,"energy":102,"type":"Buff","target":"ImplicitParty","range":0},
  {"num":65,"name":"Electric Spike","classes":"AllLords","damageType":"Physical","damage":250,"distance":10,"ag":100,"mana":0,"level":0,"energy":126,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":66,"name":"Force Wave","classes":"AllLords","damageType":"Physical","damage":50,"distance":4,"ag":0,"mana":10,"level":0,"energy":0,"type":"DirectHit","target":"ExplicitWithImplicitInRange","range":0},
  {"num":67,"name":"Stun","classes":"All","damageType":"None","damage":0,"distance":2,"ag":50,"mana":70,"level":0,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":68,"name":"Cancel Stun","classes":"All","damageType":"None","damage":0,"distance":0,"ag":30,"mana":25,"level":0,"energy":0,"type":"Other","target":"Explicit","range":0},
  {"num":69,"name":"Swell Mana","classes":"All","damageType":"None","damage":0,"distance":0,"ag":30,"mana":35,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":70,"name":"Invisibility","classes":"All","damageType":"None","damage":0,"distance":0,"ag":60,"mana":80,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":71,"name":"Cancel Invisibility","classes":"All","damageType":"None","damage":0,"distance":0,"ag":30,"mana":40,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":72,"name":"Abolish Magic","classes":"AllLords","damageType":"None","damage":0,"distance":0,"ag":70,"mana":90,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":73,"name":"Mana Rays","classes":"AllMGs","damageType":"Wizardry","damage":85,"distance":6,"ag":7,"mana":130,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":74,"name":"Fire Blast","classes":"AllLords","damageType":"Physical","damage":150,"distance":6,"ag":10,"mana":30,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":76,"name":"Plasma Storm","classes":"AllMastersAndSecondClass","damageType":"Fenrir","damage":60,"distance":6,"ag":20,"mana":50,"level":110,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":77,"name":"Infinity Arrow","classes":"MuseElfAndHighElf","damageType":"None","damage":0,"distance":6,"ag":10,"mana":50,"level":220,"energy":0,"type":"Buff","target":"Explicit","range":0},
  {"num":78,"name":"Fire Scream","classes":"AllLords","damageType":"Physical","damage":130,"distance":6,"ag":10,"mana":45,"level":0,"energy":70,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":79,"name":"Explosion","classes":"None","damageType":"Physical","damage":0,"distance":2,"ag":0,"mana":0,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":150,"name":"Generic Monster Skill","classes":"None","damageType":"None","damage":0,"distance":5,"ag":0,"mana":0,"level":0,"energy":0,"type":"Other","target":"Explicit","range":0},
  {"num":200,"name":"Summon Monster","classes":"None","damageType":"None","damage":0,"distance":0,"ag":0,"mana":40,"level":0,"energy":90,"type":"DirectHit","target":"Explicit","range":0},
  {"num":201,"name":"Magic Attack Immunity","classes":"None","damageType":"None","damage":0,"distance":0,"ag":0,"mana":40,"level":0,"energy":90,"type":"DirectHit","target":"Explicit","range":0},
  {"num":202,"name":"Physical Attack Immunity","classes":"None","damageType":"None","damage":0,"distance":0,"ag":0,"mana":40,"level":0,"energy":90,"type":"DirectHit","target":"Explicit","range":0},
  {"num":203,"name":"Potion of Bless","classes":"None","damageType":"None","damage":0,"distance":0,"ag":0,"mana":40,"level":0,"energy":90,"type":"DirectHit","target":"Explicit","range":0},
  {"num":204,"name":"Potion of Soul","classes":"None","damageType":"None","damage":0,"distance":0,"ag":0,"mana":40,"level":0,"energy":90,"type":"DirectHit","target":"Explicit","range":0},
  {"num":210,"name":"Spell of Protection","classes":"All","damageType":"None","damage":0,"distance":0,"ag":0,"mana":30,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":211,"name":"Spell of Restriction","classes":"All","damageType":"None","damage":0,"distance":3,"ag":0,"mana":30,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":212,"name":"Spell of Pursuit","classes":"All","damageType":"None","damage":0,"distance":0,"ag":0,"mana":30,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":213,"name":"Shield-Burn","classes":"All","damageType":"None","damage":0,"distance":3,"ag":0,"mana":30,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":214,"name":"Drain Life","classes":"AllSummoners","damageType":"Wizardry","damage":35,"distance":6,"ag":0,"mana":50,"level":0,"energy":150,"type":"AreaSkillExplicitTarget","target":"Explicit","range":0},
  {"num":215,"name":"Chain Lightning","classes":"AllSummoners","damageType":"Wizardry","damage":70,"distance":6,"ag":0,"mana":85,"level":0,"energy":245,"type":"AreaSkillExplicitTarget","target":"Explicit","range":0},
  {"num":217,"name":"Damage Reflection","classes":"AllSummoners","damageType":"None","damage":0,"distance":5,"ag":10,"mana":40,"level":0,"energy":375,"type":"Buff","target":"Explicit","range":0},
  {"num":218,"name":"Berserker","classes":"AllSummoners","damageType":"None","damage":0,"distance":5,"ag":50,"mana":100,"level":0,"energy":620,"type":"Buff","target":"Explicit","range":0},
  {"num":219,"name":"Sleep","classes":"AllSummoners","damageType":"None","damage":0,"distance":6,"ag":3,"mana":20,"level":0,"energy":180,"type":"Buff","target":"Explicit","range":0},
  {"num":221,"name":"Weakness","classes":"AllSummoners","damageType":"None","damage":0,"distance":6,"ag":15,"mana":50,"level":0,"energy":663,"type":"Buff","target":"Explicit","range":0},
  {"num":222,"name":"Innovation","classes":"AllSummoners","damageType":"None","damage":0,"distance":6,"ag":15,"mana":70,"level":0,"energy":912,"type":"Buff","target":"Explicit","range":0},
  {"num":223,"name":"Explosion","classes":"AllSummoners","damageType":"Curse","damage":40,"distance":6,"ag":5,"mana":90,"level":0,"energy":100,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":224,"name":"Requiem","classes":"AllSummoners","damageType":"Curse","damage":65,"distance":6,"ag":10,"mana":110,"level":0,"energy":99,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":225,"name":"Pollution","classes":"AllSummoners","damageType":"Curse","damage":80,"distance":6,"ag":15,"mana":120,"level":0,"energy":115,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":230,"name":"Lightning Shock","classes":"AllSummoners","damageType":"Wizardry","damage":95,"distance":6,"ag":7,"mana":115,"level":0,"energy":823,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":232,"name":"Strike of Destruction","classes":"BladeKnightAndBladeMaster","damageType":"Physical","damage":110,"distance":5,"ag":24,"mana":30,"level":100,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":233,"name":"Expansion of Wizardry","classes":"SoulMasterAndGrandMaster","damageType":"None","damage":0,"distance":6,"ag":50,"mana":200,"level":220,"energy":118,"type":"Buff","target":"ImplicitPlayer","range":0},
  {"num":234,"name":"Recovery","classes":"MuseElfAndHighElf","damageType":"None","damage":0,"distance":6,"ag":10,"mana":40,"level":100,"energy":37,"type":"Regeneration","target":"Explicit","range":0},
  {"num":235,"name":"Multi-Shot","classes":"MuseElfAndHighElf","damageType":"Physical","damage":40,"distance":6,"ag":7,"mana":10,"level":100,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":236,"name":"Flame Strike","classes":"AllMGs","damageType":"Physical","damage":140,"distance":3,"ag":25,"mana":20,"level":100,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":237,"name":"Gigantic Storm","classes":"AllMGs","damageType":"Wizardry","damage":110,"distance":6,"ag":10,"mana":120,"level":220,"energy":118,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":238,"name":"Chaotic Diseier","classes":"AllLords","damageType":"Physical","damage":190,"distance":6,"ag":15,"mana":50,"level":100,"energy":16,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":239,"name":"Doppelganger Self Explosion","classes":"None","damageType":"Wizardry","damage":140,"distance":3,"ag":25,"mana":20,"level":100,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":260,"name":"Killing Blow","classes":"AllFighters","damageType":"Physical","damage":0,"distance":2,"ag":0,"mana":9,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":261,"name":"Beast Uppercut","classes":"AllFighters","damageType":"Physical","damage":0,"distance":2,"ag":0,"mana":9,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":262,"name":"Chain Drive","classes":"AllFighters","damageType":"Physical","damage":0,"distance":4,"ag":20,"mana":15,"level":150,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":263,"name":"Dark Side","classes":"AllFighters","damageType":"Physical","damage":0,"distance":4,"ag":0,"mana":70,"level":180,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":264,"name":"Dragon Roar","classes":"AllFighters","damageType":"Physical","damage":0,"distance":3,"ag":30,"mana":50,"level":150,"energy":0,"type":"AreaSkillExplicitTarget","target":"Explicit","range":0},
  {"num":265,"name":"Dragon Slasher","classes":"AllFighters","damageType":"Physical","damage":0,"distance":4,"ag":100,"mana":100,"level":200,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":266,"name":"Ignore Defense","classes":"AllFighters","damageType":"Physical","damage":0,"distance":3,"ag":10,"mana":50,"level":120,"energy":404,"type":"Buff","target":"ImplicitPlayer","range":0},
  {"num":267,"name":"Increase Health","classes":"AllFighters","damageType":"Physical","damage":0,"distance":7,"ag":10,"mana":50,"level":80,"energy":132,"type":"Buff","target":"ImplicitParty","range":0},
  {"num":268,"name":"Increase Block","classes":"AllFighters","damageType":"Physical","damage":0,"distance":7,"ag":10,"mana":50,"level":50,"energy":80,"type":"Buff","target":"ImplicitParty","range":0},
  {"num":269,"name":"Charge","classes":"AllFighters","damageType":"Physical","damage":90,"distance":4,"ag":15,"mana":20,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":270,"name":"Phoenix Shot","classes":"AllFighters","damageType":"Physical","damage":0,"distance":4,"ag":0,"mana":30,"level":0,"energy":0,"type":"AreaSkillExplicitTarget","target":"Explicit","range":0},
  {"num":300,"name":"Durability Reduction (1)","classes":"AllMastersExceptFistMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":301,"name":"PvP Defence Rate Inc","classes":"AllMastersExceptFistMaster","damageType":"None","damage":12,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":302,"name":"Maximum SD increase","classes":"AllMastersExceptFistMaster","damageType":"None","damage":13,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":303,"name":"Automatic Mana Rec Inc","classes":"AllMastersExceptFistMaster","damageType":"None","damage":7,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":304,"name":"Poison Resistance Inc","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":305,"name":"Durability Reduction (2)","classes":"AllMastersExceptFistMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":306,"name":"SD Recovery Speed Inc","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":307,"name":"Automatic HP Rec Inc","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":308,"name":"Lightning Resistance Inc","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":309,"name":"Defense Increase","classes":"AllMastersExceptFistMaster","damageType":"None","damage":16,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":310,"name":"Automatic AG Rec Inc","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":311,"name":"Ice Resistance Increase","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":312,"name":"Durability Reduction (3)","classes":"AllMastersExceptFistMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":313,"name":"Defense Success Rate Inc","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":314,"name":"Cast Invincibility","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":315,"name":"Armor Set Bonus Inc","classes":"AllMastersExceptFistMaster","damageType":"None","damage":3,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":316,"name":"Vengeance","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":317,"name":"Energy Increase","classes":"AllMastersExceptFistMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":318,"name":"Stamina Increase","classes":"AllMastersExceptFistMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":319,"name":"Agility Increase","classes":"AllMastersExceptFistMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":320,"name":"Strength Increase","classes":"AllMastersExceptFistMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":321,"name":"Wing of Storm Abs PowUp","classes":"BladeMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":322,"name":"Wing of Storm Def PowUp","classes":"BladeMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":323,"name":"Iron Defense","classes":"AllMasters","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":324,"name":"Wing of Storm Att PowUp","classes":"BladeMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":325,"name":"Attack Succ Rate Inc","classes":"AllMastersExceptFistMaster","damageType":"None","damage":13,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":326,"name":"Cyclone Strengthener","classes":"BladeMaster","damageType":"Physical","damage":22,"distance":2,"ag":0,"mana":9,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":327,"name":"Slash Strengthener","classes":"BladeMaster","damageType":"Physical","damage":3,"distance":2,"ag":0,"mana":10,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":328,"name":"Falling Slash Streng","classes":"BladeMaster","damageType":"Physical","damage":3,"distance":3,"ag":0,"mana":9,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":329,"name":"Lunge Strengthener","classes":"BladeMaster","damageType":"Physical","damage":3,"distance":2,"ag":0,"mana":9,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":330,"name":"Twisting Slash Streng","classes":"BladeMaster","damageType":"Physical","damage":3,"distance":2,"ag":10,"mana":10,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":331,"name":"Rageful Blow Streng","classes":"BladeMaster","damageType":"Physical","damage":22,"distance":3,"ag":22,"mana":25,"level":170,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":332,"name":"Twisting Slash Mastery","classes":"BladeMaster","damageType":"Physical","damage":1,"distance":2,"ag":20,"mana":22,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":333,"name":"Rageful Blow Mastery","classes":"BladeMaster","damageType":"Physical","damage":1,"distance":3,"ag":30,"mana":50,"level":170,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":334,"name":"Maximum Life Increase","classes":"AllMastersExceptFistMaster","damageType":"None","damage":9,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":335,"name":"Weapon Mastery","classes":"BladeMaster","damageType":"None","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":336,"name":"Death Stab Strengthener","classes":"BladeMaster","damageType":"Physical","damage":22,"distance":2,"ag":13,"mana":15,"level":160,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":337,"name":"Strike of Destr Str","classes":"BladeMaster","damageType":"Physical","damage":22,"distance":5,"ag":24,"mana":30,"level":100,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":338,"name":"Maximum Mana Increase","classes":"AllMastersExceptFistMaster","damageType":"None","damage":9,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":339,"name":"Death Stab Proficiency","classes":"BladeMaster","damageType":"Physical","damage":7,"distance":2,"ag":26,"mana":30,"level":160,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":340,"name":"Strike of Destr Prof","classes":"BladeMaster","damageType":"Physical","damage":7,"distance":5,"ag":24,"mana":30,"level":100,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":341,"name":"Maximum AG Increase","classes":"AllMastersExceptFistMaster","damageType":"None","damage":8,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":342,"name":"Death Stab Mastery","classes":"BladeMaster","damageType":"Physical","damage":7,"distance":2,"ag":26,"mana":30,"level":160,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":343,"name":"Strike of Destr Mast","classes":"BladeMaster","damageType":"Physical","damage":1,"distance":5,"ag":24,"mana":30,"level":100,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":344,"name":"Blood Storm","classes":"BladeMaster | DuelMaster","damageType":"Physical","damage":25,"distance":3,"ag":29,"mana":87,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":345,"name":"Combo Strengthener","classes":"BladeMaster","damageType":"Physical","damage":7,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":346,"name":"Blood Storm Strengthener","classes":"BladeMaster | DuelMaster","damageType":"Physical","damage":22,"distance":3,"ag":29,"mana":87,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":347,"name":"PvP Attack Rate","classes":"AllMastersExceptFistMaster","damageType":"None","damage":14,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":348,"name":"Two-handed Sword Stren","classes":"BladeMaster | DuelMaster","damageType":"Physical","damage":4,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":349,"name":"One-handed Sword Stren","classes":"BladeMaster | DuelMaster","damageType":"Physical","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":350,"name":"Mace Strengthener","classes":"BladeMaster","damageType":"Physical","damage":3,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":351,"name":"Spear Strengthener","classes":"BladeMaster","damageType":"Physical","damage":3,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":352,"name":"Two-handed Sword Mast","classes":"BladeMaster | DuelMaster","damageType":"Physical","damage":5,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":353,"name":"One-handed Sword Mast","classes":"BladeMaster | DuelMaster","damageType":"Physical","damage":23,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":354,"name":"Mace Mastery","classes":"BladeMaster","damageType":"Physical","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":355,"name":"Spear Mastery","classes":"BladeMaster","damageType":"Physical","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":356,"name":"Swell Life Strengt","classes":"BladeMaster","damageType":"None","damage":7,"distance":0,"ag":26,"mana":24,"level":120,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":357,"name":"Mana Reduction","classes":"AllMastersExceptFistMaster","damageType":"None","damage":18,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":358,"name":"Monster Attack SD Inc","classes":"AllMastersExceptFistMaster","damageType":"None","damage":11,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":359,"name":"Monster Attack Life Inc","classes":"AllMastersExceptFistMaster","damageType":"None","damage":6,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":360,"name":"Swell Life Proficiency","classes":"BladeMaster","damageType":"None","damage":7,"distance":0,"ag":28,"mana":26,"level":120,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":361,"name":"Minimum Attack Power Inc","classes":"BladeMaster | DuelMaster | LordEmperor","damageType":"Physical","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":362,"name":"Monster Attack Mana Inc","classes":"AllMastersExceptFistMaster","damageType":"None","damage":6,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":363,"name":"Swell Life Mastery","classes":"BladeMaster","damageType":"None","damage":7,"distance":0,"ag":30,"mana":28,"level":120,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":364,"name":"Maximum Attack Power Inc","classes":"BladeMaster | DuelMaster | LordEmperor","damageType":"Physical","damage":3,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":366,"name":"Inc crit damage rate","classes":"AllMastersExceptFistMaster","damageType":"None","damage":7,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":367,"name":"Restores all Mana","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":368,"name":"Restores all HP","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":369,"name":"Inc exc damage rate","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":370,"name":"Inc double damage rate","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":371,"name":"Inc chance of ignore Def","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":372,"name":"Restores all SD","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":373,"name":"Inc triple damage rate","classes":"AllMastersExceptFistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":374,"name":"Eternal Wings Abs PowUp","classes":"GrandMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":375,"name":"Eternal Wings Def PowUp","classes":"GrandMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":377,"name":"Eternal Wings Att PowUp","classes":"GrandMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":378,"name":"Flame Strengthener","classes":"GrandMaster","damageType":"Wizardry","damage":3,"distance":6,"ag":0,"mana":55,"level":35,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":379,"name":"Lightning Strengthener","classes":"GrandMaster","damageType":"Wizardry","damage":3,"distance":6,"ag":0,"mana":20,"level":13,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":380,"name":"Expansion of Wiz Streng","classes":"GrandMaster","damageType":"Wizardry","damage":1,"distance":6,"ag":55,"mana":220,"level":220,"energy":118,"type":"DirectHit","target":"Explicit","range":0},
  {"num":381,"name":"Inferno Strengthener","classes":"GrandMaster","damageType":"Wizardry","damage":22,"distance":0,"ag":0,"mana":220,"level":88,"energy":200,"type":"DirectHit","target":"Explicit","range":0},
  {"num":382,"name":"Blast Strengthener","classes":"GrandMaster","damageType":"Wizardry","damage":22,"distance":3,"ag":0,"mana":165,"level":80,"energy":150,"type":"DirectHit","target":"Explicit","range":0},
  {"num":383,"name":"Expansion of Wiz Mas","classes":"GrandMaster","damageType":"Wizardry","damage":1,"distance":6,"ag":55,"mana":220,"level":220,"energy":118,"type":"DirectHit","target":"Explicit","range":0},
  {"num":384,"name":"Poison Strengthener","classes":"GrandMaster","damageType":"Wizardry","damage":3,"distance":6,"ag":0,"mana":46,"level":30,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":385,"name":"Evil Spirit Streng","classes":"GrandMaster","damageType":"Wizardry","damage":22,"distance":6,"ag":0,"mana":108,"level":50,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":386,"name":"Magic Mastery","classes":"GrandMaster","damageType":"None","damage":22,"distance":0,"ag":0,"mana":0,"level":50,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":387,"name":"Decay Strengthener","classes":"GrandMaster","damageType":"Wizardry","damage":22,"distance":6,"ag":10,"mana":120,"level":96,"energy":243,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":388,"name":"Hellfire Strengthener","classes":"GrandMaster","damageType":"Wizardry","damage":3,"distance":4,"ag":0,"mana":176,"level":60,"energy":100,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":389,"name":"Ice Strengthener","classes":"GrandMaster","damageType":"Wizardry","damage":3,"distance":6,"ag":0,"mana":42,"level":25,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":390,"name":"Meteor Strengthener","classes":"GrandMaster","damageType":"Wizardry","damage":4,"distance":6,"ag":0,"mana":13,"level":21,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":391,"name":"Ice Storm Strengthener","classes":"GrandMaster","damageType":"Wizardry","damage":22,"distance":6,"ag":5,"mana":110,"level":93,"energy":223,"type":"DirectHit","target":"Explicit","range":0},
  {"num":392,"name":"Nova Strengthener","classes":"GrandMaster","damageType":"Wizardry","damage":22,"distance":6,"ag":49,"mana":198,"level":100,"energy":258,"type":"DirectHit","target":"Explicit","range":0},
  {"num":393,"name":"Ice Storm Mastery","classes":"GrandMaster","damageType":"Wizardry","damage":1,"distance":6,"ag":5,"mana":110,"level":93,"energy":223,"type":"DirectHit","target":"Explicit","range":0},
  {"num":394,"name":"Meteor Mastery","classes":"GrandMaster","damageType":"Wizardry","damage":1,"distance":6,"ag":0,"mana":14,"level":21,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":395,"name":"Nova Cast Strengthener","classes":"GrandMaster","damageType":"Wizardry","damage":22,"distance":6,"ag":49,"mana":198,"level":100,"energy":258,"type":"DirectHit","target":"Explicit","range":0},
  {"num":397,"name":"One-handed Staff Stren","classes":"GrandMaster | DuelMaster","damageType":"Wizardry","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":398,"name":"Two-handed Staff Stren","classes":"GrandMaster | DuelMaster","damageType":"Wizardry","damage":4,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":399,"name":"Shield Strengthener","classes":"GrandMaster","damageType":"None","damage":10,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":400,"name":"One-handed Staff Mast","classes":"GrandMaster | DuelMaster","damageType":"None","damage":23,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":401,"name":"Two-handed Staff Mast","classes":"GrandMaster | DuelMaster","damageType":"Wizardry","damage":5,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":402,"name":"Shield Mastery","classes":"GrandMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":403,"name":"Soul Barrier Strength","classes":"GrandMaster","damageType":"None","damage":7,"distance":6,"ag":24,"mana":77,"level":77,"energy":126,"type":"DirectHit","target":"Explicit","range":0},
  {"num":404,"name":"Soul Barrier Proficie","classes":"GrandMaster","damageType":"None","damage":10,"distance":6,"ag":26,"mana":84,"level":77,"energy":126,"type":"DirectHit","target":"Explicit","range":0},
  {"num":405,"name":"Minimum Wizardry Inc","classes":"GrandMaster | DuelMaster","damageType":"None","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":406,"name":"Soul Barrier Mastery","classes":"GrandMaster","damageType":"None","damage":7,"distance":6,"ag":28,"mana":92,"level":77,"energy":126,"type":"DirectHit","target":"Explicit","range":0},
  {"num":407,"name":"Maximum Wizardry Inc","classes":"GrandMaster | DuelMaster","damageType":"None","damage":3,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":409,"name":"Illusion Wings Abs PowUp","classes":"HighElf","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":410,"name":"Illusion Wings Def PowUp","classes":"HighElf","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":411,"name":"Multi-Shot Streng","classes":"HighElf","damageType":"Physical","damage":22,"distance":6,"ag":7,"mana":11,"level":100,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":412,"name":"Illusion Wings Att PowUp","classes":"HighElf","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":413,"name":"Heal Strengthener","classes":"HighElf","damageType":"Physical","damage":22,"distance":6,"ag":0,"mana":22,"level":8,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":414,"name":"Triple Shot Strengthener","classes":"HighElf","damageType":"Physical","damage":22,"distance":6,"ag":0,"mana":5,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":415,"name":"Summoned Monster Str (1)","classes":"HighElf","damageType":"None","damage":16,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":416,"name":"Penetration Strengthener","classes":"HighElf","damageType":"Physical","damage":22,"distance":6,"ag":11,"mana":10,"level":130,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":417,"name":"Defense Increase Str","classes":"HighElf","damageType":"None","damage":22,"distance":6,"ag":0,"mana":33,"level":13,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":418,"name":"Triple Shot Mastery","classes":"HighElf","damageType":"Physical","damage":0,"distance":6,"ag":0,"mana":9,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":419,"name":"Summoned Monster Str (2)","classes":"HighElf","damageType":"None","damage":16,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":420,"name":"Attack Increase Str","classes":"HighElf","damageType":"None","damage":22,"distance":6,"ag":0,"mana":44,"level":18,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":421,"name":"Weapon Mastery","classes":"HighElf","damageType":"None","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":422,"name":"Attack Increase Mastery","classes":"HighElf","damageType":"None","damage":22,"distance":6,"ag":0,"mana":48,"level":18,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":423,"name":"Defense Increase Mastery","classes":"HighElf","damageType":"None","damage":22,"distance":6,"ag":0,"mana":36,"level":13,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":424,"name":"Ice Arrow Strengthener","classes":"HighElf","damageType":"Physical","damage":22,"distance":8,"ag":18,"mana":15,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":425,"name":"Cure","classes":"HighElf","damageType":"None","damage":0,"distance":6,"ag":10,"mana":72,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":426,"name":"Party Healing","classes":"HighElf","damageType":"None","damage":0,"distance":6,"ag":12,"mana":66,"level":0,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":427,"name":"Poison Arrow","classes":"HighElf","damageType":"Physical","damage":27,"distance":6,"ag":27,"mana":22,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":428,"name":"Summoned Monster Str (3)","classes":"HighElf","damageType":"None","damage":16,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":429,"name":"Party Healing Str","classes":"HighElf","damageType":"None","damage":22,"distance":6,"ag":13,"mana":72,"level":0,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":430,"name":"Bless","classes":"HighElf","damageType":"None","damage":0,"distance":6,"ag":18,"mana":108,"level":0,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":431,"name":"Multi-Shot Mastery","classes":"HighElf","damageType":"Physical","damage":1,"distance":6,"ag":8,"mana":12,"level":100,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":432,"name":"Summon Satyros","classes":"HighElf","damageType":"None","damage":0,"distance":0,"ag":52,"mana":525,"level":0,"energy":280,"type":"DirectHit","target":"Explicit","range":0},
  {"num":433,"name":"Bless Strengthener","classes":"HighElf","damageType":"None","damage":10,"distance":6,"ag":20,"mana":118,"level":0,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":434,"name":"Poison Arrow Str","classes":"HighElf","damageType":"Physical","damage":22,"distance":6,"ag":29,"mana":24,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":435,"name":"Bow Strengthener","classes":"HighElf","damageType":"None","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":436,"name":"Crossbow Strengthener","classes":"HighElf","damageType":"None","damage":3,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":437,"name":"Shield Strengthener","classes":"HighElf","damageType":"None","damage":10,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":438,"name":"Bow Mastery","classes":"HighElf","damageType":"None","damage":23,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":439,"name":"Crossbow Mastery","classes":"HighElf","damageType":"None","damage":5,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":440,"name":"Shield Mastery","classes":"HighElf","damageType":"None","damage":15,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":441,"name":"Infinity Arrow Str","classes":"HighElf","damageType":"None","damage":1,"distance":6,"ag":11,"mana":55,"level":220,"energy":0,"type":"Buff","target":"Explicit","range":0},
  {"num":442,"name":"Minimum Att Power Inc","classes":"HighElf","damageType":"Physical","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":443,"name":"Maximum Att Power Inc","classes":"HighElf","damageType":"Physical","damage":3,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":445,"name":"DimensionWings Abs PowUp","classes":"DimensionMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":446,"name":"DimensionWings Def PowUp","classes":"DimensionMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":447,"name":"DimensionWings Att PowUp","classes":"DimensionMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":448,"name":"Fire Tome Strengthener","classes":"DimensionMaster","damageType":"Curse","damage":3,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":449,"name":"Wind Tome Strengthener","classes":"DimensionMaster","damageType":"Curse","damage":3,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":450,"name":"Lightning Tome Stren","classes":"DimensionMaster","damageType":"Curse","damage":3,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":451,"name":"Fire Tome Mastery","classes":"DimensionMaster","damageType":"Curse","damage":7,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":452,"name":"Wind Tome Mastery","classes":"DimensionMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":453,"name":"Lightning Tome Mastery","classes":"DimensionMaster","damageType":"Curse","damage":7,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":454,"name":"Sleep Strengthener","classes":"DimensionMaster","damageType":"None","damage":1,"distance":6,"ag":7,"mana":30,"level":40,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":455,"name":"Chain Lightning Str","classes":"DimensionMaster","damageType":"Wizardry","damage":22,"distance":6,"ag":0,"mana":103,"level":75,"energy":75,"type":"AreaSkillExplicitTarget","target":"Explicit","range":0},
  {"num":456,"name":"Lightning Shock Str","classes":"DimensionMaster","damageType":"Wizardry","damage":22,"distance":6,"ag":10,"mana":125,"level":93,"energy":216,"type":"DirectHit","target":"Explicit","range":0},
  {"num":457,"name":"Magic Mastery","classes":"DimensionMaster","damageType":"Curse","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":458,"name":"Drain Life Strengthener","classes":"DimensionMaster","damageType":"Wizardry","damage":22,"distance":6,"ag":0,"mana":57,"level":35,"energy":93,"type":"DirectHit","target":"Explicit","range":0},
  {"num":459,"name":"Weakness Strengthener","classes":"DimensionMaster","damageType":"Curse","damage":3,"distance":6,"ag":17,"mana":55,"level":93,"energy":173,"type":"DirectHit","target":"Explicit","range":0},
  {"num":460,"name":"Innovation Strengthener","classes":"DimensionMaster","damageType":"Curse","damage":3,"distance":6,"ag":17,"mana":77,"level":111,"energy":201,"type":"DirectHit","target":"Explicit","range":0},
  {"num":461,"name":"Blind","classes":"DimensionMaster","damageType":"Curse","damage":0,"distance":3,"ag":25,"mana":115,"level":0,"energy":201,"type":"DirectHit","target":"Explicit","range":0},
  {"num":462,"name":"Drain Life Mastery","classes":"DimensionMaster","damageType":"Curse","damage":17,"distance":6,"ag":0,"mana":62,"level":35,"energy":93,"type":"DirectHit","target":"Explicit","range":0},
  {"num":463,"name":"Blind Strengthener","classes":"DimensionMaster","damageType":"Curse","damage":1,"distance":3,"ag":27,"mana":126,"level":0,"energy":201,"type":"DirectHit","target":"Explicit","range":0},
  {"num":465,"name":"Stick Strengthener","classes":"DimensionMaster","damageType":"Curse","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":466,"name":"Other World Tome Streng","classes":"DimensionMaster","damageType":"Curse","damage":3,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":467,"name":"Stick Mastery","classes":"DimensionMaster","damageType":"Curse","damage":5,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":468,"name":"Other World Tome Mastery","classes":"DimensionMaster","damageType":"None","damage":23,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":469,"name":"Berserker Strengthener","classes":"DimensionMaster","damageType":"Curse","damage":7,"distance":5,"ag":75,"mana":150,"level":83,"energy":181,"type":"DirectHit","target":"Explicit","range":0},
  {"num":470,"name":"Berserker Proficiency","classes":"DimensionMaster","damageType":"Curse","damage":7,"distance":5,"ag":82,"mana":165,"level":83,"energy":181,"type":"DirectHit","target":"Explicit","range":0},
  {"num":471,"name":"Minimum Wiz/Curse Inc","classes":"DimensionMaster","damageType":"None","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":472,"name":"Berserker Mastery","classes":"DimensionMaster","damageType":"Curse","damage":10,"distance":5,"ag":90,"mana":181,"level":83,"energy":181,"type":"DirectHit","target":"Explicit","range":0},
  {"num":473,"name":"Maximum Wiz/Curse Inc","classes":"DimensionMaster","damageType":"None","damage":3,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":475,"name":"Wing of Ruin Abs PowUp","classes":"DuelMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":476,"name":"Wing of Ruin Def PowUp","classes":"DuelMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":478,"name":"Wing of Ruin Att PowUp","classes":"DuelMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":479,"name":"Cyclone Strengthener","classes":"DuelMaster","damageType":"Physical","damage":22,"distance":2,"ag":0,"mana":9,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":480,"name":"Lightning Strengthener","classes":"DuelMaster","damageType":"Physical","damage":3,"distance":6,"ag":0,"mana":20,"level":13,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":481,"name":"Twisting Slash Stren","classes":"DuelMaster","damageType":"Physical","damage":3,"distance":2,"ag":10,"mana":10,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":482,"name":"Power Slash Streng","classes":"DuelMaster","damageType":"None","damage":3,"distance":5,"ag":0,"mana":15,"level":0,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":483,"name":"Flame Strengthener","classes":"DuelMaster","damageType":"Physical","damage":3,"distance":6,"ag":0,"mana":55,"level":35,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":484,"name":"Blast Strengthener","classes":"DuelMaster","damageType":"Physical","damage":22,"distance":3,"ag":0,"mana":165,"level":80,"energy":150,"type":"DirectHit","target":"Explicit","range":0},
  {"num":485,"name":"Weapon Mastery","classes":"DuelMaster","damageType":"None","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":486,"name":"Inferno Strengthener","classes":"DuelMaster","damageType":"Physical","damage":22,"distance":0,"ag":0,"mana":220,"level":88,"energy":200,"type":"DirectHit","target":"Explicit","range":0},
  {"num":487,"name":"Evil Spirit Strengthen","classes":"DuelMaster","damageType":"Physical","damage":22,"distance":6,"ag":0,"mana":108,"level":50,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":488,"name":"Magic Mastery","classes":"DuelMaster","damageType":"None","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":489,"name":"Ice Strengthener","classes":"DuelMaster","damageType":"Physical","damage":3,"distance":6,"ag":0,"mana":42,"level":25,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":490,"name":"Blood Attack Strengthen","classes":"DuelMaster","damageType":"None","damage":22,"distance":3,"ag":22,"mana":15,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":491,"name":"Ice Mastery","classes":"DuelMaster","damageType":"Physical","damage":1,"distance":6,"ag":0,"mana":46,"level":25,"energy":100,"type":"DirectHit","target":"Explicit","range":0},
  {"num":492,"name":"Flame Strike Strengthen","classes":"DuelMaster","damageType":"Physical","damage":22,"distance":3,"ag":37,"mana":30,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":493,"name":"Fire Slash Mastery","classes":"DuelMaster","damageType":"None","damage":7,"distance":3,"ag":24,"mana":17,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":494,"name":"Flame Strike Mastery","classes":"DuelMaster","damageType":"Physical","damage":7,"distance":3,"ag":40,"mana":33,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":495,"name":"Earth Prison","classes":"GrandMaster | DuelMaster","damageType":"Physical","damage":26,"distance":3,"ag":15,"mana":180,"level":0,"energy":127,"type":"DirectHit","target":"Explicit","range":0},
  {"num":496,"name":"Gigantic Storm Str","classes":"DuelMaster","damageType":"Physical","damage":22,"distance":6,"ag":11,"mana":132,"level":220,"energy":118,"type":"DirectHit","target":"Explicit","range":0},
  {"num":497,"name":"Earth Prison Str","classes":"GrandMaster | DuelMaster","damageType":"Physical","damage":22,"distance":3,"ag":17,"mana":198,"level":0,"energy":127,"type":"DirectHit","target":"Explicit","range":0},
  {"num":504,"name":"Emperor Cape Abs PowUp","classes":"LordEmperor","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":505,"name":"Emperor Cape Def PowUp","classes":"LordEmperor","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":506,"name":"Adds Command Stat","classes":"LordEmperor","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":507,"name":"Emperor Cape Att PowUp","classes":"LordEmperor","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":508,"name":"Fire Burst Streng","classes":"LordEmperor","damageType":"Physical","damage":22,"distance":6,"ag":0,"mana":25,"level":74,"energy":20,"type":"DirectHit","target":"Explicit","range":0},
  {"num":509,"name":"Force Wave Streng","classes":"LordEmperor","damageType":"Physical","damage":3,"distance":4,"ag":0,"mana":15,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":510,"name":"Dark Horse Streng (1)","classes":"LordEmperor","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":511,"name":"Critical DMG Inc PowUp","classes":"LordEmperor","damageType":"None","damage":3,"distance":0,"ag":75,"mana":75,"level":82,"energy":25,"type":"DirectHit","target":"Explicit","range":0},
  {"num":512,"name":"Earthshake Streng","classes":"LordEmperor","damageType":"Physical","damage":22,"distance":10,"ag":75,"mana":0,"level":0,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":513,"name":"Weapon Mastery","classes":"LordEmperor","damageType":"None","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":514,"name":"Fire Burst Mastery","classes":"LordEmperor","damageType":"Physical","damage":1,"distance":6,"ag":0,"mana":27,"level":74,"energy":20,"type":"DirectHit","target":"Explicit","range":0},
  {"num":515,"name":"Crit DMG Inc PowUp (2)","classes":"LordEmperor","damageType":"None","damage":10,"distance":0,"ag":82,"mana":82,"level":82,"energy":25,"type":"DirectHit","target":"Explicit","range":0},
  {"num":516,"name":"Earthshake Mastery","classes":"LordEmperor","damageType":"Physical","damage":1,"distance":10,"ag":75,"mana":0,"level":0,"energy":0,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":517,"name":"Crit DMG Inc PowUp (3)","classes":"LordEmperor","damageType":"None","damage":7,"distance":0,"ag":100,"mana":100,"level":82,"energy":25,"type":"DirectHit","target":"Explicit","range":0},
  {"num":518,"name":"Fire Scream Stren","classes":"LordEmperor","damageType":"Physical","damage":22,"distance":6,"ag":11,"mana":45,"level":102,"energy":32,"type":"DirectHit","target":"Explicit","range":0},
  {"num":519,"name":"Electric Spark Streng","classes":"LordEmperor","damageType":"Physical","damage":3,"distance":10,"ag":150,"mana":0,"level":92,"energy":29,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":520,"name":"Fire Scream Mastery","classes":"LordEmperor","damageType":"Physical","damage":5,"distance":6,"ag":12,"mana":49,"level":102,"energy":32,"type":"DirectHit","target":"Explicit","range":0},
  {"num":521,"name":"Iron Defense","classes":"LordEmperor","damageType":"None","damage":28,"distance":0,"ag":29,"mana":64,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":522,"name":"Critical Damage Inc M","classes":"LordEmperor","damageType":"None","damage":1,"distance":0,"ag":110,"mana":110,"level":82,"energy":25,"type":"DirectHit","target":"Explicit","range":0},
  {"num":523,"name":"Chaotic Diseier Str","classes":"LordEmperor","damageType":"Physical","damage":22,"distance":6,"ag":22,"mana":75,"level":100,"energy":16,"type":"AreaSkillAutomaticHits","target":"Explicit","range":0},
  {"num":524,"name":"Iron Defense Str","classes":"LordEmperor","damageType":"None","damage":3,"distance":0,"ag":31,"mana":70,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":526,"name":"Dark Spirit Str","classes":"LordEmperor","damageType":"None","damage":3,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":527,"name":"Scepter Strengthener","classes":"LordEmperor","damageType":"Physical","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":528,"name":"Shield Strengthener","classes":"LordEmperor","damageType":"None","damage":10,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":529,"name":"Use Scepter : Pet Str","classes":"LordEmperor","damageType":"None","damage":3,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":530,"name":"Dark Spirit Str (2)","classes":"LordEmperor","damageType":"None","damage":7,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":531,"name":"Scepter Mastery","classes":"LordEmperor","damageType":"None","damage":5,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":532,"name":"Shield Mastery","classes":"LordEmperor","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":533,"name":"Command Attack Inc","classes":"LordEmperor","damageType":"None","damage":20,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":534,"name":"Dark Spirit Str (3)","classes":"LordEmperor","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":535,"name":"Pet Durability Str","classes":"LordEmperor","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":536,"name":"Dark Spirit Str (4)","classes":"LordEmperor","damageType":"None","damage":23,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":538,"name":"Dark Spirit Str (5)","classes":"LordEmperor","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":539,"name":"Spirit Lord","classes":"LordEmperor","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":551,"name":"Killing Blow Strengthener","classes":"FistMaster","damageType":"Physical","damage":22,"distance":2,"ag":0,"mana":10,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":552,"name":"Beast Uppercut Strengthener","classes":"FistMaster","damageType":"Physical","damage":22,"distance":2,"ag":0,"mana":10,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":554,"name":"Killing Blow Mastery","classes":"FistMaster","damageType":"Physical","damage":1,"distance":2,"ag":0,"mana":10,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":555,"name":"Beast Uppercut Mastery","classes":"FistMaster","damageType":"Physical","damage":1,"distance":2,"ag":0,"mana":10,"level":0,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":557,"name":"Weapon Mastery","classes":"FistMaster","damageType":"None","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":558,"name":"Chain Drive Strengthener","classes":"FistMaster","damageType":"Physical","damage":22,"distance":4,"ag":22,"mana":22,"level":150,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":559,"name":"Dark Side Strengthener","classes":"FistMaster","damageType":"Physical","damage":22,"distance":4,"ag":0,"mana":84,"level":180,"energy":0,"type":"DirectHit","target":"Explicit","range":0},
  {"num":560,"name":"Dragon Roar Strengthener","classes":"FistMaster","damageType":"Physical","damage":22,"distance":3,"ag":33,"mana":60,"level":150,"energy":0,"type":"AreaSkillExplicitTarget","target":"Explicit","range":0},
  {"num":568,"name":"Equipped Weapon Strengthener","classes":"FistMaster","damageType":"None","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":569,"name":"Def SuccessRate IncPowUp","classes":"FistMaster","damageType":"Physical","damage":22,"distance":7,"ag":11,"mana":55,"level":50,"energy":30,"type":"DirectHit","target":"Explicit","range":0},
  {"num":571,"name":"Equipped Weapon Mastery","classes":"FistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":572,"name":"DefSuccessRate IncMastery","classes":"FistMaster","damageType":"Physical","damage":22,"distance":7,"ag":12,"mana":60,"level":50,"energy":30,"type":"DirectHit","target":"Explicit","range":0},
  {"num":573,"name":"Stamina Increase Strengthener","classes":"FistMaster","damageType":"Physical","damage":5,"distance":7,"ag":11,"mana":55,"level":80,"energy":35,"type":"DirectHit","target":"Explicit","range":0},
  {"num":578,"name":"Durability Reduction (1)","classes":"FistMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":579,"name":"Increase PvP Defense Rate","classes":"FistMaster","damageType":"None","damage":29,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":580,"name":"Increase Maximum SD","classes":"FistMaster","damageType":"None","damage":33,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":581,"name":"Increase Mana Recovery Rate","classes":"FistMaster","damageType":"None","damage":7,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":582,"name":"Increase Poison Resistance","classes":"FistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":583,"name":"Durability Reduction (2)","classes":"FistMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":584,"name":"Increase SD Recovery Rate","classes":"FistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":585,"name":"Increase HP Recovery Rate","classes":"FistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":586,"name":"Increase Lightning Resistance","classes":"FistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":587,"name":"Increases Defense","classes":"FistMaster","damageType":"None","damage":35,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":588,"name":"Increases AG Recovery Rate","classes":"FistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":589,"name":"Increase Ice Resistance","classes":"FistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":590,"name":"Durability Reduction(3)","classes":"FistMaster","damageType":"None","damage":17,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":591,"name":"Increase Defense Success Rate","classes":"FistMaster","damageType":"None","damage":1,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":592,"name":"Cast Invincibility","classes":"FistMaster","damageType":"None","damage":38,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":599,"name":"Increase Attack Success Rate","classes":"FistMaster","damageType":"None","damage":30,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":600,"name":"Increase Maximum HP","classes":"FistMaster","damageType":"None","damage":34,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":601,"name":"Increase Maximum Mana","classes":"FistMaster","damageType":"None","damage":34,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":602,"name":"Increase Maximum AG","classes":"FistMaster","damageType":"None","damage":37,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":603,"name":"Increase PvP Attack Rate","classes":"FistMaster","damageType":"None","damage":31,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":604,"name":"Decrease Mana","classes":"FistMaster","damageType":"None","damage":18,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":605,"name":"Recover SD from Monster Kills","classes":"FistMaster","damageType":"None","damage":11,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":606,"name":"Recover HP from Monster Kills","classes":"FistMaster","damageType":"None","damage":6,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":607,"name":"Increase Minimum Attack Power","classes":"FistMaster","damageType":"None","damage":22,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":608,"name":"Recover Mana Monster Kills","classes":"FistMaster","damageType":"None","damage":6,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":609,"name":"Increase Maximum Attack Power","classes":"FistMaster","damageType":"None","damage":3,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":610,"name":"Increases Crit Damage Chance","classes":"FistMaster","damageType":"None","damage":38,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":611,"name":"Recover Mana Fully","classes":"FistMaster","damageType":"None","damage":38,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":612,"name":"Recovers HP Fully","classes":"FistMaster","damageType":"None","damage":38,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":613,"name":"Increase Exc Damage Chance","classes":"FistMaster","damageType":"None","damage":38,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":614,"name":"Increase Double Damage Chance","classes":"FistMaster","damageType":"None","damage":38,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":615,"name":"Increase Ignore Def Chance","classes":"FistMaster","damageType":"None","damage":38,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":616,"name":"Recovers SD Fully","classes":"FistMaster","damageType":"None","damage":38,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
  {"num":617,"name":"Increase Triple Damage Chance","classes":"FistMaster","damageType":"None","damage":38,"distance":0,"ag":0,"mana":0,"level":0,"energy":0,"type":"PassiveBoost","target":"Explicit","range":0},
];

const byNumber = new Map(SKILL_DEFINITIONS.map(s => [s.num, s]));

// Mu La Ronda: an active master skill behaves as the skill it replaces - OpenMU
// copies the replaced skill's type, target, damage type and area onto it
// (`AddMasterSkillDefinition`). The table above lists them all as DirectHit,
// so Twisting Slash Strengthener went out as a single-target hit the server
// did nothing with.
for (const [master, replaced] of Object.entries(MASTER_REPLACES)) {
  const def = byNumber.get(Number(master));
  const base = byNumber.get(masterRoot(replaced));
  if (!def || !base || def.type === 'PassiveBoost') continue;
  byNumber.set(def.num, {
    ...def,
    type: base.type,
    target: base.target,
    damageType: base.damageType,
    range: base.range,
    distance: def.distance || base.distance,
  });
}

export function skillDefinition(num: number): SkillDefinition | undefined {
  return byNumber.get(num);
}
